name: 'PR labels'
description: |
  Extract labels from the PR that this build belongs to and make them 
  available to other actions.
author: joerick
outputs:
  labels: # id of output
    description: |
      The labels on this PR. A dictionary containing `true` where a label
      exists
runs:
  using: 'node12'
  main: 'index.js'
