on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get PR labels
        id: pr-labels
        uses: ./ # Uses an action in the root directory
      - run: |
          env | grep GITHUB_PR_LABEL || true
      - run: |
          echo "labels was there."
        if: steps.pr-labels.outputs.labels
